o use bundle in zip format, download jar as fallback

diff --git a/nx-get b/nx-get
--- a/nx-get
+++ b/nx-get
@@ -16,10 +16,30 @@ $v
 EOF
 fi
 
+# $tmp is handled by devhelper-common
+
 if [ "$USE_GAV_DIR" = "true" ]
 then
     dir="$g.$a-$v-remote"
     mkdir -p "$dir"
-    opts="-C $dir"
+    opts="-d $dir"
 fi
-curl "$NEXUS/service/local/artifact/maven/redirect?r=$r&g=$g&a=$a&c=bundle&e=tar.gz&v=$v" --netrc-optional -L | tar xz $opts
+
+echo "Downloading bundle..."
+if curl -# "$NEXUS/service/local/artifact/maven/redirect?r=$r&g=$g&a=$a&c=bundle&e=zip&v=$v" -f --netrc-optional -L -o "$tmp" 
+then
+    echo "Extracting bundle..."
+    unzip -q -o "$tmp" $opts
+    exit
+fi
+
+echo "Downloading jar file..."
+# fall back to default main artifact
+if curl -# "$NEXUS/service/local/artifact/maven/redirect?r=$r&g=$g&a=$a&e=jar&v=$v" -f --netrc-optional -L -o "$tmp"
+then
+    mv "$tmp" "$dir/$a-$v.jar"
+    exit
+fi
+
+echo >&2 "Could not find GAV $g:$a:$v"
+exit 1
